### ISSUE TITLE
Failed to run some commands

### ISSUE THREAD

**Issue by leeminghao** [joelagnel/adeb#33]
root@localhost:/usr/share/bcc/tools# filetop 5 10
sh: modprobe: command not found
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module)
chdir(/lib/modules/4.9.186-perf-g4773f96/build): No such file or directory
Traceback (most recent call last):
  File "/usr/share/bcc/tools/filetop", line 161, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 343, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

**Comment by leeminghao** [comment]
CONFIG_IKHEADERS=y on my device

**Comment by leeminghao** [comment]
I have resolved this issue like this:

https://github.com/novelinux/linux-4.x.y/tree/master/perf/eBPF
